services:
  - type: web
    name: carbon-price-api
    env: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app ./cmd/server
    startCommand: ./app
    envVars:
      - key: PORT
        value: 10000
      - key: GIN_MODE
        value: release
    healthCheckPath: /health
    autoDeploy: true 