services:
  - type: web
    name: carbon-price-api
    env: go
    buildCommand: go build -o main ./cmd/server
    startCommand: ./main
    envVars:
      - key: PORT
        value: 10000
      - key: GIN_MODE
        value: release
    healthCheckPath: /health
    autoDeploy: true 